#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else false; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any, with write_env's quoting undone.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value sq="'\\''"; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value="${line#*=}"
  if [[ "$value" == \'*\' ]]; then value="${value:1:${#value}-2}"; value="${value//"$sq"/\'}"; fi
  printf '%s' "$value"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret), edited
# with Readline. Fails at EOF with no input.
ask() {
  local key="$1" prompt="$2" current input s=$'\001' e=$'\002' p rc=0
  current=$(_existing "$key" || true)
  # Readline needs the colour codes wrapped in \001..\002 to place the cursor.
  p="  $s$BOLD$e$prompt$s$RESET$e "
  [[ -n "$current" ]] && p+="$s$DIM$e[Enter keeps current]$s$RESET$e "
  read -e -r -p "$p" input || rc=1
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input rc=0
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || rc=1
  printf '\n'
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY='VALUE' into ENV_FILE (replaces any existing
# line). Idempotent. Creates ENV_FILE at mode 0600; writes through a symlink
# and keeps an existing file's mode.
write_env() {
  local key="$1" value="$2" tmp sq="'\\''"
  [[ -e "$ENV_FILE" ]] || (umask 077 && : > "$ENV_FILE")
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf "%s='%s'\n" "$key" "${value//\'/$sq}" >> "$tmp"
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

# All generated local configuration is ignored; secrets live outside the repo.
VITA_REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)
cd "$VITA_REPO"
VITA_LOCAL="$VITA_REPO/.scratch/independent-web-v1/local"
umask 077
mkdir -p "$VITA_LOCAL"
ENV_FILE="$VITA_LOCAL/cutover.env"
if [[ -L "$VITA_LOCAL" || -L "$ENV_FILE" || ( -e "$ENV_FILE" && ! -f "$ENV_FILE" ) ]]; then
  printf '拒绝通过链接或非普通文件保存部署配置。\n' >&2; exit 1
fi
chmod 700 "$VITA_LOCAL"
[[ ! -e "$ENV_FILE" ]] || chmod 600 "$ENV_FILE"

record() {
  local record_key="$1" record_prompt="$2" record_pattern="${3:-.+}"
  ask "$record_key" "$record_prompt"
  if [[ ! "${!record_key}" =~ $record_pattern ]]; then warn "输入无效；已停止，请核对后重跑。"; exit 1; fi
  write_env "$record_key" "${!record_key}"
}
gate() { confirm "$1" || { warn '未确认；停止在当前步骤，未记录验收通过。'; exit 1; }; }
show_cmd() { printf '  '; printf '%q ' "$@"; printf '\n'; }
origin() {
  record "$1" "$2"
  node --input-type=module - "${!1}" <<'JS'
const url = new URL(process.argv[2]);
if (url.protocol !== 'https:' || url.username || url.password || url.pathname !== '/' || url.search || url.hash) throw new Error('必须是没有路径或凭据的 HTTPS origin');
JS
}

banner 'Vita Log · Cloudflare 部署与切换（需要本人操作）'
say '步骤：账号/套餐 → Pages → 两个 D1 → 访问隔离 → Secret/离线目录 → schema → 预览发布 → 预览验收 → 生产迁移 → 备份恢复/定时任务 → 公网切换。'
say '向导只生成本地配置和私有 Secret 文件、展示命令与记录本人确认；远端命令由你在另一个终端执行。'
say '每一步只做一次；重跑时先核对实际状态，已有迁移或已经落库的数据不得重新导入。'
gate '确认上述阶段顺序与值的落点？配置在 ignored local/，密码不进仓库，验收只记录脱敏结果'

stage 'Cloudflare 账号、套餐与本机工具'
open_url 'https://dash.cloudflare.com/'
step '选择目标账号；记录 Account ID。在 Workers & Pages 的套餐/用量页核对实际 CPU 额度。'
record CF_ACCOUNT_ID '目标 Account ID：' '^[a-fA-F0-9]{32}$'
record CF_CPU_BUDGET_MS '本人确认的单次 HTTP CPU 额度（毫秒）：' '^[0-9]+([.][0-9]+)?$'
open_url 'https://developers.cloudflare.com/workers/wrangler/install-and-update/'
step '安装/选择受信任的 Wrangler，确认当前账号；向导不自动下载。Node 需 >=22.5，项目依赖需已安装。'
show_cmd wrangler --version
show_cmd wrangler whoami
command -v wrangler >/dev/null || { warn 'Wrangler 尚未安装。请完成工具准备后重跑。'; exit 1; }
node --input-type=module -e 'const [major,minor]=process.versions.node.split(".").map(Number); if(major<22 || (major===22 && minor<5)) process.exit(1)'
gate '已核对 Wrangler 当前账号与以上 Account ID 一致，且套餐信息来自目标账号'

stage 'Pages 项目与生产/预览分支'
open_url 'https://developers.cloudflare.com/pages/get-started/direct-upload/'
open_url 'https://dash.cloudflare.com/'
step 'Workers & Pages → 选择现有 Pages 项目，或创建 Direct Upload 项目。不要用控制台拖拽上传 Functions。'
step '已有 Git 项目先暂停自动生产部署；保持原配置和上一次部署信息，后面生成的 Wrangler 文件将成为配置事实来源。'
record CF_PAGES_PROJECT '真实 Pages 项目名：' '^[a-z0-9][a-z0-9-]*$'
record CF_PRODUCTION_BRANCH '真实生产分支名：' '^[a-zA-Z0-9][a-zA-Z0-9_/-]*$'
record CF_PREVIEW_BRANCH '此次预览分支名（与生产不同）：' '^[a-zA-Z0-9][a-zA-Z0-9_/-]*$'
[[ "$CF_PRODUCTION_BRANCH" != "$CF_PREVIEW_BRANCH" ]] || { warn '预览与生产分支不能相同'; exit 1; }
show_cmd wrangler pages project create "$CF_PAGES_PROJECT" --production-branch "$CF_PRODUCTION_BRANCH"
note '仅当项目尚未创建时，才执行上面的 create 命令；已有项目不得重建。'
gate '项目已存在、生产分支已核对、自动切换不会抢先发布'

stage '独立的预览/生产 D1'
open_url 'https://developers.cloudflare.com/d1/get-started/'
open_url 'https://dash.cloudflare.com/'
step 'Storage & databases → D1 → 创建/选择两个独立数据库；在各数据库详情复制真实名称和 Database ID。'
record CF_PREVIEW_DB_NAME '预览 D1 名称：' '^[a-zA-Z0-9][a-zA-Z0-9_-]*$'
record CF_PREVIEW_DB_ID '预览 D1 UUID：' '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
record CF_PRODUCTION_DB_NAME '生产 D1 名称：' '^[a-zA-Z0-9][a-zA-Z0-9_-]*$'
record CF_PRODUCTION_DB_ID '生产 D1 UUID：' '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
[[ "$(printf %s "$CF_PREVIEW_DB_ID" | tr '[:upper:]' '[:lower:]')" != "$(printf %s "$CF_PRODUCTION_DB_ID" | tr '[:upper:]' '[:lower:]')" ]] || { warn '两个环境不能绑定同一数据库'; exit 1; }
gate '两个 D1 的账号、名称和 ID 已分别核对；预览只使用合成数据'

stage '封闭 pages.dev、自定义域名与历史部署入口'
open_url 'https://developers.cloudflare.com/pages/platform/known-issues/#enable-access-on-your-pagesdev-domain'
open_url 'https://dash.cloudflare.com/'
step '按官方说明启用预览 Access，并覆盖项目 pages.dev 根域名、所有 hash/分支域名及自定义域名。默认预览保护不覆盖根域名。'
step 'Zero Trust → Access controls → Applications：限制本人访问；为运维 CLI 配置 Service Auth 策略与服务令牌。'
step '自定义域名先在 Pages → Custom domains 关联并等待 HTTPS 正常，但保持本人访问隔离。'
step '发布后用未登录浏览器逐个核验。仅隐藏 DNS、只保护首页或设置 noindex 都不能封闭健康 API。'
gate '访问隔离策略已准备，真实健康数据迁入前会验证所有入口，Access 服务令牌仅保存在受限凭据文件'

stage '受限离线目录与本人 Secret'
open_url 'https://developers.cloudflare.com/pages/functions/bindings/#environment-variables'
step '按 docs/cloudflare-cutover.md 准备仓库之外的 0700 备份目录、预览/生产各自的 0600 凭据 JSON。'
record CF_BACKUP_DIRECTORY '仓库之外的受限备份目录（绝对路径）：' '^/'
record CF_PREVIEW_CREDENTIALS '预览本人凭据 JSON（绝对路径）：' '^/'
record CF_PRODUCTION_CREDENTIALS '生产本人凭据 JSON（绝对路径）：' '^/'
record CF_PREVIEW_USERNAME '预览 VITA_LOG_OWNER_USERNAME：'
record CF_PRODUCTION_USERNAME '生产 VITA_LOG_OWNER_USERNAME：'
export CF_BACKUP_DIRECTORY CF_PREVIEW_CREDENTIALS CF_PRODUCTION_CREDENTIALS CF_PREVIEW_USERNAME CF_PRODUCTION_USERNAME
node --import tsx --input-type=module - <<'JS'
import { lstatSync, realpathSync, writeFileSync } from 'node:fs';
import { join, relative, isAbsolute } from 'node:path';
import { randomUUID } from 'node:crypto';
import { readOwnerFile } from './server/d1-owner-file.ts';
import { describePasswordProblem } from './server/credential-policy.ts';
import { createOwnerCredential } from './functions/_lib/owner-credentials.ts';
import { describeCredentialProblem } from './functions/_lib/password.ts';
const root = realpathSync(process.env.CF_BACKUP_DIRECTORY);
const info = lstatSync(process.env.CF_BACKUP_DIRECTORY);
const rel = relative(realpathSync('.'), root);
if (!info.isDirectory() || (info.mode & 0o777) !== 0o700 || (!rel.startsWith('../') && !isAbsolute(rel))) throw new Error('需要仓库之外的 0700 真实目录');
for (const kind of ['PREVIEW', 'PRODUCTION']) {
  const file = process.env[`CF_${kind}_CREDENTIALS`];
  const credentialRel = relative(realpathSync('.'), realpathSync(file));
  if (!credentialRel.startsWith('../') && !isAbsolute(credentialRel)) throw new Error('凭据必须在仓库之外');
  const credentials = readOwnerFile(file);
  if (credentials.username !== process.env[`CF_${kind}_USERNAME`]) throw new Error('账号与配置不一致');
  // Both checks are the same ones the runtime applies, run here so a credential
  // the deployment cannot use is refused before it ever reaches Cloudflare. The
  // failure it prevents — deployed and unauthenticatable in the same step, with
  // a login error that points at the wrong subsystem — is expensive to diagnose.
  const weak = describePasswordProblem(credentials.password);
  if (weak) throw new Error(`密码不符合门槛：${weak}`);
  const credential = await createOwnerCredential(credentials.password);
  const unusable = describeCredentialProblem(credential);
  if (unusable) throw new Error(unusable);
  const path = join(root, `${kind.toLowerCase()}-${randomUUID()}.secret.txt`);
  writeFileSync(path, credential, { mode: 0o600, flag: 'wx' });
  console.log(`${kind} Secret 受限文件：${path}`);
}
JS
open_url 'https://dash.cloudflare.com/'
step 'Pages → 项目 → Settings → Variables and Secrets：分别选择 Preview / Production，设置 VITA_LOG_OWNER_USERNAME，添加类型为 Secret 的 VITA_LOG_OWNER_CREDENTIAL。'
step 'Secret 从刚生成的对应环境私有文件复制；不粘贴到聊天、配置、验收或 CI。重新部署后生效。'
gate '两个环境的 Secret 已由本人配置；没有使用历史公开凭据；私有文件未进入仓库'

stage '生成真实配置、初始化 schema 和增量迁移'
export CF_ACCOUNT_ID CF_PAGES_PROJECT CF_PREVIEW_DB_NAME CF_PREVIEW_DB_ID CF_PRODUCTION_DB_NAME CF_PRODUCTION_DB_ID
CF_CONFIG_PATH="$VITA_LOCAL/wrangler.json"
export CF_CONFIG_PATH
node --input-type=module - <<'JS'
import { readFileSync, writeFileSync, existsSync, lstatSync } from 'node:fs';
import { resolve } from 'node:path';
const env = process.env;
const binding = kind => [{ binding: 'VITA_LOG_DB', database_name: env[`CF_${kind}_DB_NAME`], database_id: env[`CF_${kind}_DB_ID`], migrations_dir: resolve('functions/migrations') }];
const vars = kind => ({ VITA_LOG_OWNER_USERNAME: env[`CF_${kind}_USERNAME`] });
const config = { name: env.CF_PAGES_PROJECT, account_id: env.CF_ACCOUNT_ID, pages_build_output_dir: resolve('dist'), compatibility_date: '2026-10-08', d1_databases: binding('PREVIEW'), vars: vars('PREVIEW'), env: { preview: { d1_databases: binding('PREVIEW'), vars: vars('PREVIEW') }, production: { d1_databases: binding('PRODUCTION'), vars: vars('PRODUCTION') } } };
const content = JSON.stringify(config, null, 2) + '\n';
if (existsSync(env.CF_CONFIG_PATH)) {
  if (!lstatSync(env.CF_CONFIG_PATH).isFile() || readFileSync(env.CF_CONFIG_PATH, 'utf8') !== content) throw new Error('已有配置与当前输入不同；请先人工保留和核对，不覆盖');
} else writeFileSync(env.CF_CONFIG_PATH, content, { flag: 'wx', mode: 0o600 });
JS
write_env CF_CONFIG_PATH "$CF_CONFIG_PATH"
for VITA_ENV in preview production; do
  say "$VITA_ENV：核对目标 D1，再执行基础 schema 和全部增量迁移；不要重建数据库。"
  show_cmd wrangler d1 execute VITA_LOG_DB --config "$CF_CONFIG_PATH" --env "$VITA_ENV" --remote --file functions/schema.sql
  show_cmd wrangler d1 migrations apply VITA_LOG_DB --config "$CF_CONFIG_PATH" --env "$VITA_ENV" --remote
  show_cmd wrangler d1 execute VITA_LOG_DB --config "$CF_CONFIG_PATH" --env "$VITA_ENV" --remote --command 'SELECT COUNT(*) AS health_rows FROM health_state; SELECT name FROM sqlite_master WHERE type = '\''table'\'';'
done
gate '已核对并手动执行迁移；两个库的 schema 已验证；生产 health_state 为空，或已导入则停止本次首次迁移'

stage '预览发布、来源预览与真实登录 CPU'
show_cmd npm run build:cloudflare
show_cmd node scripts/verify-release.mjs
show_cmd wrangler pages deploy dist --config "$CF_CONFIG_PATH" --project-name "$CF_PAGES_PROJECT" --branch "$CF_PREVIEW_BRANCH"
gate '已核对预览分支与 D1，执行预览发布，并核验所有未授权入口受保护'
origin CF_PREVIEW_ORIGIN '控制台中真实预览 HTTPS origin：'
record CF_PREVIEW_SQLITE '按 runbook 创建的合成 SQLite 来源（绝对路径）：' '^/'
show_cmd npm run d1:cutover -- --origin "$CF_PREVIEW_ORIGIN" --credentials "$CF_PREVIEW_CREDENTIALS" --sqlite "$CF_PREVIEW_SQLITE" --directory "$CF_BACKUP_DIRECTORY"
say '核对预览后，在上条命令追加 --confirm --source-sha256 <刚显示的摘要>；首次迁移后不能重放。'
open_url 'https://developers.cloudflare.com/pages/functions/metrics/'
step '真实预览登录必须成功；记录客户端耗时，并在目标平台观测 CPU。墙钟耗时不替代 CPU 额度。'
step '若登录返回 503 且文案是「本人凭据无法在当前环境校验」，那是 Secret 里的凭据缺陷（迭代数超过平台上限 100000），不是 CPU 余量不足：升级套餐没有用，换用迭代数不超过上限的凭据。'
record CF_LOGIN_DURATION_MS '成功登录的实测墙钟耗时（毫秒）：' '^[0-9]+([.][0-9]+)?$'
record CF_LOGIN_CPU_MS '目标平台观测的登录 CPU（毫秒）：' '^[0-9]+([.][0-9]+)?$'
export CF_LOGIN_CPU_MS CF_CPU_BUDGET_MS
node --input-type=module -e 'const budget=Number(process.env.CF_CPU_BUDGET_MS), used=Number(process.env.CF_LOGIN_CPU_MS); if(!(budget>0 && used>=0 && used<budget)) throw new Error("CPU 余量不足，停止；升级套餐或变更迭代数须另行记录决定")'
gate '已确认 100000 次 PBKDF2 在当前套餐成功，CPU 证据是目标平台观测，未静默下调迭代数'

stage '预览安全、审计、平台限流与恢复演练'
open_url 'https://developers.cloudflare.com/waf/rate-limiting-rules/create-zone-dashboard/'
step '按 runbook 验收矩阵配置并验证平台规则，覆盖 login、写入、备份/导出；封闭 pages.dev 绕过路径。套餐不支持完整规则时停止，不以 isolate 内计数代替。'
step '合成数据验证会话到期/注销、CSRF、匿名写入、备份泄露、冲突、故障、审计事务/分页/保留及 schema 旧行保留。'
step '按 d1-backup-recovery.md 在预览 D1 做 JSON 恢复与 Time Travel，恢复后撤销旧会话。unknown 元数据缺失属于契约故障注入；无法在原生 D1 注入时保持未验证。'
step '在 .scratch/independent-web-v1/evidence/06.1-06-cloudflare.md 逐项记录脱敏结果，pending 不能当 pass。'
gate '预览验收矩阵全部有目标环境证据；未出现阻断项，回滚和 D1 绑定均已核对'

stage '隔离状态下的生产发布、冻结来源与首次迁移'
origin CF_PRODUCTION_ORIGIN '实际生产 HTTPS origin（仍限制本人访问）：'
record CF_SOURCE_SQLITE '本机真实 SQLite 来源（绝对路径）：' '^/'
step '停止本机健康数据写入，保留原 SQLite 和现有备份；之后在线 D1 是唯一事实来源。'
show_cmd wrangler pages deploy dist --config "$CF_CONFIG_PATH" --project-name "$CF_PAGES_PROJECT" --branch "$CF_PRODUCTION_BRANCH"
gate '已核对生产数据库为空、Secret/迁移/产物一致，并手动发布；所有入口仍隔离'
show_cmd npm run d1:cutover -- --origin "$CF_PRODUCTION_ORIGIN" --credentials "$CF_PRODUCTION_CREDENTIALS" --sqlite "$CF_SOURCE_SQLITE" --directory "$CF_BACKUP_DIRECTORY"
say '核对类型数量、日期、营养和设置后，追加 --confirm --source-sha256 <生产预览摘要> 执行一次。'
say '只有 reconciled=true 且迁移前后 JSON/SQLite 均落盘才继续。中断时先检查在线版本，绝不清库重试。'
gate '本人已确认真实来源并执行首次迁移，对账通过且完整备份落盘；原 SQLite 保留'

stage '生产备份、定时任务、恢复与会话撤销'
show_cmd npm run d1:backup -- backup --origin "$CF_PRODUCTION_ORIGIN" --credentials "$CF_PRODUCTION_CREDENTIALS" --directory "$CF_BACKUP_DIRECTORY"
open_url 'https://developers.cloudflare.com/d1/reference/time-travel/'
step '按备份指南，在维护窗口确认真实 D1 与 bookmark 后演练平台恢复；先保留安全副本，随后清除 owner_session、核对 schema/完整数据。由本人确认覆盖。'
step '使用 ops/d1-backup.launchd.plist.example，替换全部真实路径/origin；权限 0600 日志置于 0700 目录。先运行成功，再由本人安装到 LaunchAgents。'
step '实际触发任务并核对退出码、新备份文件、权限及导出时间；仅 plist 语法通过不能验收定时备份。'
gate '生产恢复、历史会话撤销、备份失败停止恢复、版本冲突和定时任务实际运行均已有证据'

stage '自定义域名公网切换与生产验收'
open_url 'https://developers.cloudflare.com/pages/configuration/custom-domains/'
step '最后核对证据矩阵：CPU、访问隔离、迁移/备份、平台限流、Time Travel、schema、回滚均已通过。'
gate '确认允许真实生产健康看板公开，且已经准备立即重新封闭访问的回滚路径'
step '由本人解除生产自定义域名的访问隔离；预览与 pages.dev 历史入口继续受保护。逐个检查没有通过别名绕过平台限流。'
step '无痕访客读取；本人保存后访客刷新见新数据；本人注销后编辑失败。真实桌面与移动浏览器按矩阵复验。'
step '出现故障立即重新封闭访问。回滚旧 Pages 部署不回滚 D1；数据回滚先备份并由本人确认。'
gate '生产验收已取证且没有 pending/blocker，旧入口状态与回滚路径已记录'
finish
say '以上是本人执行记录；agent 尚未独立验收。核对证据后再关闭 #06.1-06 与 #06.1-05，不能只凭向导运行结束关票。'
